name: 'Check for version update'
# on: pull-request
on:
  push: true

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout required for dorny/paths-filter to work
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: main
          filters: |
            create-loop:
              - 'create-loop/**'
            loop-templates:
              - 'loop-templates/**'
            vscode-extension:
              - 'vscode-extension/**'

      - run: chmod +x "${GITHUB_WORKSPACE}/.github/scripts/check_version.sh"

      - if: steps.changes.outputs.create-loop == 'true'
        name: 'Confirming create-loop version update'
        run: ${GITHUB_WORKSPACE}/.github/scripts/check_version.sh create-loop

      - if: steps.changes.outputs.loop-templates == 'true'
        name: 'Confirming loop-templates version update'
        run: ${GITHUB_WORKSPACE}/.github/scripts/check_version.sh loop-templates

      - if: steps.changes.outputs.vscode-extension == 'true'
        name: 'Confirming vscode-extension version update'
        run: ${GITHUB_WORKSPACE}/.github/scripts/check_version.sh vscode-extension
