name: NPM Publishing
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # `secrets.NPM_TOKEN` references a GitHub Secret configured for this repo or organization,
      # and is used to authenticate for the NPM publish command.
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm set audit false

      - name: Publish to NPM
        run: |
          npm ci
          npm run build --if-present
          printf '\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish --access public
